name: IaC Scan and Push Metrics

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
      - '.github/workflows/iac-scan.yml'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip jq
          wget https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -O tfsec && chmod +x tfsec && sudo mv tfsec /usr/local/bin/
          pip install checkov
          curl -L https://github.com/tenable/terrascan/releases/latest/download/terrascan_linux_amd64.zip -o terrascan.zip
          unzip terrascan.zip && chmod +x terrascan && sudo mv terrascan /usr/local/bin/

      - name: Run tfsec
        id: tfsec
        run: |
          tfsec terraform --format json > tfsec.json
          echo "TFSEC_ISSUES=$(jq '.results | length' tfsec.json)" >> $GITHUB_ENV

      - name: Run checkov
        id: checkov
        run: |
          checkov -d terraform -o json > checkov.json
          echo "CHECKOV_ISSUES=$(jq '[.results.failed_checks[]] | length' checkov.json)" >> $GITHUB_ENV

      - name: Run terrascan
        id: terrascan
        run: |
          terrascan scan -t terraform -o json > terrascan.json
          echo "TERRASCAN_ISSUES=$(jq '.results.violations | length' terrascan.json)" >> $GITHUB_ENV

      - name: Push metrics to Prometheus Pushgateway
        run: |
          chmod +x scripts/push_metrics.sh
          ./scripts/push_metrics.sh $TFSEC_ISSUES $CHECKOV_ISSUES $TERRASCAN_ISSUES
